spring.application.name=demo-tecnica

# Driver
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# URL de conexion: jdbc:mariadb://HOST:PUERTO/NOMBRE_DB
# spring.datasource.url=jdbc:mariadb://localhost:12345/db
spring.datasource.url=${SPRING_DATASOURCE_URL}

# Usuario y contrasena
#spring.datasource.username=dev
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
#spring.datasource.password=dev123
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

# Hibernate / JPA
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect